services:
  mongodb_prod:
    image: mongo:6
    container_name: mongodb_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data-prod:/data/db
    networks:
      - shortener_net
    profiles:
      - prod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb_dev:
    image: mongo:6
    container_name: mongodb_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - shortener_net
    profiles:
      - dev
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb-test:
    image: mongo:6.0
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=url-shortener-test

  shortener_app:
    image: ghcr.io/adrianmfuentes/url-shortener:latest
    container_name: shortener_app
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_BASE_URL=https://url-shortener.amfserver.duckdns.org
      - SPRING_DATA_MONGODB_HOST=mongodb_prod
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=${DB_NAME}
      - SPRING_DATA_MONGODB_USERNAME=${DB_USER}
      - SPRING_DATA_MONGODB_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
    depends_on:
      mongodb_prod:
        condition: service_healthy
    restart: on-failure
    networks:
      - shortener_net
      - npm_proxy_net
    profiles:
      - prod

  shortener_app_dev:
    build: .
    container_name: shortener_app_dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APP_BASE_URL=http://localhost:8080
      - SPRING_DATA_MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb_dev:27017/${DB_NAME}?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      mongodb_dev:
        condition: service_healthy
    restart: on-failure
    networks:
      - shortener_net
    profiles:
      - dev

networks:
  shortener_net:
    driver: bridge
  npm_proxy_net:
    external: true
    name: nginx-proxy-manager_default

volumes:
  mongo-data-prod:
