services:
  mongodb_prod:
    image: mongo:6
    container_name: mongodb_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data-prod:/data/db
    networks:
      - shortener_net
    profiles:
      - prod

  mongodb_dev:
    image: mongo:6
    container_name: mongodb_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - shortener_net
    profiles:
      - dev

  shortener_app:
    image: ghcr.io/adrianmfuentes/url-shortener:latest
    container_name: shortener_app
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_BASE_URL=https://url-shortener.amfserver.duckdns.org
      - SPRING_DATA_MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb_prod:27017/${DB_NAME}?authSource=admin
    depends_on:
      - mongodb_prod
    networks:
      - shortener_net
      - npm_proxy_net
    profiles:
      - prod

  shortener_app_dev:
    build: .
    container_name: shortener_app_dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APP_BASE_URL=http://localhost:8080
      - SPRING_DATA_MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb_dev:27017/${DB_NAME}?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      - mongodb_dev
    networks:
      - shortener_net
    profiles:
      - dev

networks:
  shortener_net:
    driver: bridge
  npm_proxy_net:
    external: true
    name: nginx-proxy-manager_default

volumes:
  mongo-data-prod:
