services:
  mongodb_prod:
    image: mongo:6
    container_name: mongodb_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: shortener_db
    volumes:
      - mongo-data-prod:/data/db # Usamos volumen de docker para persistencia real
    networks:
      - shortener_net

  shortener_app:
    image: ghcr.io/adrianmfuentes/url-shortener:latest
    container_name: shortener_app
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - APP_BASE_URL=https://url-shortener.amfserver.duckdns.org
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password123@mongodb_prod:27017/shortener_db?authSource=admin
    depends_on:
      - mongodb_prod
    networks:
      - shortener_net
      - npm_proxy_net

networks:
  shortener_net:
    driver: bridge
  npm_proxy_net:
    external: true
    name: nginx-proxy-manager_default

volumes:
  mongo-data-prod: