name: Java CI/CD con Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Definimos el servicio de base de datos
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y Ejecutar Tests
        run: |
          mvn -B clean test \
          -Dspring.mongodb.embedded.version=none \
          -Dspring.data.mongodb.port=27017 \
          -DargLine="-XX:+EnableDynamicAgentLoading -Xshare:off"