name: Java CI/CD con Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y Ejecutar Tests
        run: mvn -B clean test -DargLine="-XX:+EnableDynamicAgentLoading -Xshare:off"

      - name: Ejecutar Test de Rendimiento
        run: mvn test -Dtest=UrlPerformanceTest

      - name: Generar Artefacto JAR
        run: mvn -B package -DskipTests --file pom.xml

      - name: Subir Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: url-shortener-app
          path: target/*.jar